# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pawsooon/Vivado/tor_wizyjny/video_passthrough_kria/video_passthrough_kria.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/ip_3/bd_d10d_vfb_0_0_slo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d10d_vfb_0_0_slo || ORIG_REF_NAME==bd_d10d_vfb_0_0_slo} -quiet] -quiet

# IP: /home/pawsooon/Vivado/tor_wizyjny/video_passthrough_kria/video_passthrough_kria.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/ip_2/bd_d10d_vfb_0_0_sli.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d10d_vfb_0_0_sli || ORIG_REF_NAME==bd_d10d_vfb_0_0_sli} -quiet] -quiet

# IP: /home/pawsooon/Vivado/tor_wizyjny/video_passthrough_kria/video_passthrough_kria.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/ip_1/bd_d10d_vfb_0_0_axisswitch.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d10d_vfb_0_0_axisswitch || ORIG_REF_NAME==bd_d10d_vfb_0_0_axisswitch} -quiet] -quiet

# IP: /home/pawsooon/Vivado/tor_wizyjny/video_passthrough_kria/video_passthrough_kria.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/ip_0/bd_d10d_vfb_0_0_axis_converter.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d10d_vfb_0_0_axis_converter || ORIG_REF_NAME==bd_d10d_vfb_0_0_axis_converter} -quiet] -quiet

# XDC: /home/pawsooon/Vivado/tor_wizyjny/video_passthrough_kria/video_passthrough_kria.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/ip_1/bd_d10d_vfb_0_0_axisswitch_ooc.xdc

# XDC: /home/pawsooon/Vivado/tor_wizyjny/video_passthrough_kria/video_passthrough_kria.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_d10d_vfb_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_vfb_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/pawsooon/Vivado/tor_wizyjny/video_passthrough_kria/video_passthrough_kria.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/ip_3/bd_d10d_vfb_0_0_slo.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d10d_vfb_0_0_slo || ORIG_REF_NAME==bd_d10d_vfb_0_0_slo} -quiet] -quiet

# IP: /home/pawsooon/Vivado/tor_wizyjny/video_passthrough_kria/video_passthrough_kria.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/ip_2/bd_d10d_vfb_0_0_sli.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d10d_vfb_0_0_sli || ORIG_REF_NAME==bd_d10d_vfb_0_0_sli} -quiet] -quiet

# IP: /home/pawsooon/Vivado/tor_wizyjny/video_passthrough_kria/video_passthrough_kria.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/ip_1/bd_d10d_vfb_0_0_axisswitch.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d10d_vfb_0_0_axisswitch || ORIG_REF_NAME==bd_d10d_vfb_0_0_axisswitch} -quiet] -quiet

# IP: /home/pawsooon/Vivado/tor_wizyjny/video_passthrough_kria/video_passthrough_kria.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/ip_0/bd_d10d_vfb_0_0_axis_converter.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d10d_vfb_0_0_axis_converter || ORIG_REF_NAME==bd_d10d_vfb_0_0_axis_converter} -quiet] -quiet

# XDC: /home/pawsooon/Vivado/tor_wizyjny/video_passthrough_kria/video_passthrough_kria.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/ip_1/bd_d10d_vfb_0_0_axisswitch_ooc.xdc

# XDC: /home/pawsooon/Vivado/tor_wizyjny/video_passthrough_kria/video_passthrough_kria.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_d10d_vfb_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_vfb_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
