# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pawsooon/Vivado/binaryzacja/video_passthrough_kria/video_passthrough_kria.srcs/sources_1/ip/divider_32_21_1/divider_32_21_1.xci
# IP: The module: 'divider_32_21_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/pawsooon/Vivado/binaryzacja/video_passthrough_kria/video_passthrough_kria.gen/sources_1/ip/divider_32_21_1/src/mult_32_21_lm/mult_32_21_lm.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_32_21_lm || ORIG_REF_NAME==mult_32_21_lm} -quiet] -quiet

# IP: /home/pawsooon/Vivado/binaryzacja/video_passthrough_kria/video_passthrough_kria.srcs/sources_1/ip/divider_32_21_1/divider_32_21_1.xci
# IP: The module: 'divider_32_21_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/pawsooon/Vivado/binaryzacja/video_passthrough_kria/video_passthrough_kria.gen/sources_1/ip/divider_32_21_1/src/mult_32_21_lm/mult_32_21_lm.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_32_21_lm || ORIG_REF_NAME==mult_32_21_lm} -quiet] -quiet
