// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_1_v_demosaic_0_0_DebayerRandBatG (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        imgRB_dout,
        imgRB_num_data_valid,
        imgRB_fifo_cap,
        imgRB_empty_n,
        imgRB_read,
        imgRgb_din,
        imgRgb_num_data_valid,
        imgRgb_fifo_cap,
        imgRgb_full_n,
        imgRgb_write,
        height,
        width,
        bayerPhase_c_dout,
        bayerPhase_c_num_data_valid,
        bayerPhase_c_fifo_cap,
        bayerPhase_c_empty_n,
        bayerPhase_c_read
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [29:0] imgRB_dout;
input  [1:0] imgRB_num_data_valid;
input  [1:0] imgRB_fifo_cap;
input   imgRB_empty_n;
output   imgRB_read;
output  [29:0] imgRgb_din;
input  [1:0] imgRgb_num_data_valid;
input  [1:0] imgRgb_fifo_cap;
input   imgRgb_full_n;
output   imgRgb_write;
input  [10:0] height;
input  [10:0] width;
input  [15:0] bayerPhase_c_dout;
input  [1:0] bayerPhase_c_num_data_valid;
input  [1:0] bayerPhase_c_fifo_cap;
input   bayerPhase_c_empty_n;
output   bayerPhase_c_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg imgRB_read;
reg imgRgb_write;
reg bayerPhase_c_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    bayerPhase_c_blk_n;
wire   [10:0] loopHeight_fu_185_p2;
reg   [10:0] loopHeight_reg_400;
wire   [0:0] x_phase_fu_191_p1;
reg   [0:0] x_phase_reg_405;
reg   [14:0] trunc_ln825_1_i_reg_410;
wire   [10:0] add_ln833_fu_205_p2;
reg   [10:0] add_ln833_reg_415;
wire   [11:0] zext_ln833_fu_219_p1;
reg   [11:0] zext_ln833_reg_420;
wire    ap_CS_fsm_state2;
reg   [9:0] p_0_0_0_0_01231_12329_lcssa2371_i_load_reg_428;
wire   [0:0] icmp_ln833_fu_223_p2;
reg   [9:0] p_0_1_0_0_01232_12332_lcssa2373_i_load_reg_433;
reg   [9:0] p_0_2_0_0_01233_12335_lcssa2375_i_load_reg_438;
reg   [9:0] p_lcssa24082442_i_load_reg_443;
reg   [9:0] p_lcssa24092444_i_load_reg_448;
reg   [9:0] p_lcssa24102446_i_load_reg_453;
reg   [9:0] p_0_0_0_0_011942411_lcssa2448_i_load_reg_458;
reg   [9:0] p_0_1_0_0_011952413_lcssa2450_i_load_reg_463;
reg   [9:0] p_0_2_0_0_011962415_lcssa2452_i_load_reg_468;
reg   [9:0] p_0_0_01230_223982418_lcssa2454_i_load_reg_473;
reg   [9:0] p_0_0_01229_224002420_lcssa2456_i_load_reg_478;
reg   [9:0] p_0_0_01228_224022422_lcssa2458_i_load_reg_483;
wire   [14:0] xor_i_fu_284_p2;
reg   [14:0] xor_i_reg_488;
wire   [0:0] cmp58_i_fu_289_p2;
reg   [0:0] cmp58_i_reg_493;
wire   [0:0] cmp202_i_fu_294_p2;
reg   [0:0] cmp202_i_reg_498;
wire   [11:0] out_y_i_fu_305_p2;
reg   [11:0] out_y_i_reg_503;
wire    ap_CS_fsm_state3;
wire   [29:0] lineBuffer_val_V_q1;
wire   [29:0] lineBuffer_val_V_2_q1;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_start;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_done;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_idle;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_ready;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_imgRB_read;
wire   [29:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_imgRgb_din;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_imgRgb_write;
wire   [10:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_address0;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_ce0;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_we0;
wire   [29:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_d0;
wire   [10:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_address1;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_ce1;
wire   [10:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_address0;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_ce0;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_we0;
wire   [29:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_d0;
wire   [10:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_address1;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_ce1;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01228_224022421_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01228_224022421_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01229_224002419_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01229_224002419_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01230_223982417_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01230_223982417_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_2_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out1;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out1_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out2;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out2_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_2_0_0_01233_12334_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_2_0_0_01233_12334_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_1_0_0_01232_12331_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_1_0_0_01232_12331_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_0_0_01231_12328_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_0_0_01231_12328_i_out_ap_vld;
reg    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_start_reg;
wire    ap_CS_fsm_state4;
reg   [9:0] p_0_0_01228_224022422_lcssa2458_i_fu_114;
reg   [9:0] p_0_0_01229_224002420_lcssa2456_i_fu_110;
reg   [9:0] p_0_0_01230_223982418_lcssa2454_i_fu_106;
reg   [9:0] p_0_2_0_0_011962415_lcssa2452_i_fu_102;
reg   [9:0] p_0_1_0_0_011952413_lcssa2450_i_fu_98;
reg   [9:0] p_0_0_0_0_011942411_lcssa2448_i_fu_94;
reg   [9:0] p_lcssa24102446_i_fu_90;
reg   [9:0] p_lcssa24092444_i_fu_86;
reg   [9:0] p_lcssa24082442_i_fu_82;
reg   [9:0] p_0_2_0_0_01233_12335_lcssa2375_i_fu_78;
reg   [9:0] p_0_1_0_0_01232_12332_lcssa2373_i_fu_74;
reg   [9:0] p_0_0_0_0_01231_12329_lcssa2371_i_fu_70;
reg   [10:0] y_fu_66;
wire   [10:0] y_6_fu_228_p2;
reg    ap_block_state1;
wire   [0:0] empty_130_fu_270_p1;
wire   [0:0] out_y_cast_i_fu_274_p2;
wire   [14:0] and305_cast_i_fu_280_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_start_reg = 1'b0;
end

design_1_v_demosaic_0_0_DebayerRandBatG_lineBuffer_val_V_RAM_AUTO_1R1W #(
    .DataWidth( 30 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
lineBuffer_val_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_address0),
    .ce0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_ce0),
    .we0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_we0),
    .d0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_d0),
    .address1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_address1),
    .ce1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_ce1),
    .q1(lineBuffer_val_V_q1)
);

design_1_v_demosaic_0_0_DebayerRandBatG_lineBuffer_val_V_RAM_AUTO_1R1W #(
    .DataWidth( 30 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
lineBuffer_val_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_address0),
    .ce0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_ce0),
    .we0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_we0),
    .d0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_d0),
    .address1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_address1),
    .ce1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_ce1),
    .q1(lineBuffer_val_V_2_q1)
);

design_1_v_demosaic_0_0_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2 grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_start),
    .ap_done(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_done),
    .ap_idle(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_idle),
    .ap_ready(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_ready),
    .imgRB_dout(imgRB_dout),
    .imgRB_num_data_valid(2'd0),
    .imgRB_fifo_cap(2'd0),
    .imgRB_empty_n(imgRB_empty_n),
    .imgRB_read(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_imgRB_read),
    .imgRgb_din(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_imgRgb_din),
    .imgRgb_num_data_valid(2'd0),
    .imgRgb_fifo_cap(2'd0),
    .imgRgb_full_n(imgRgb_full_n),
    .imgRgb_write(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_imgRgb_write),
    .p_0_0_01228_224022422_lcssa2458_i(p_0_0_01228_224022422_lcssa2458_i_load_reg_483),
    .p_0_0_01229_224002420_lcssa2456_i(p_0_0_01229_224002420_lcssa2456_i_load_reg_478),
    .p_0_0_01230_223982418_lcssa2454_i(p_0_0_01230_223982418_lcssa2454_i_load_reg_473),
    .p_0_2_0_0_011962415_lcssa2452_i(p_0_2_0_0_011962415_lcssa2452_i_load_reg_468),
    .p_0_1_0_0_011952413_lcssa2450_i(p_0_1_0_0_011952413_lcssa2450_i_load_reg_463),
    .p_0_0_0_0_011942411_lcssa2448_i(p_0_0_0_0_011942411_lcssa2448_i_load_reg_458),
    .p_lcssa24102446_i(p_lcssa24102446_i_load_reg_453),
    .p_lcssa24092444_i(p_lcssa24092444_i_load_reg_448),
    .p_lcssa24082442_i(p_lcssa24082442_i_load_reg_443),
    .p_0_2_0_0_01233_12335_lcssa2375_i(p_0_2_0_0_01233_12335_lcssa2375_i_load_reg_438),
    .p_0_1_0_0_01232_12332_lcssa2373_i(p_0_1_0_0_01232_12332_lcssa2373_i_load_reg_433),
    .p_0_0_0_0_01231_12329_lcssa2371_i(p_0_0_0_0_01231_12329_lcssa2371_i_load_reg_428),
    .add_ln833_i(add_ln833_reg_415),
    .x_phase_i(x_phase_reg_405),
    .xor_i(xor_i_reg_488),
    .out_y_i(out_y_i_reg_503),
    .lineBuffer_val_V_2_i_address0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_address0),
    .lineBuffer_val_V_2_i_ce0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_ce0),
    .lineBuffer_val_V_2_i_we0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_we0),
    .lineBuffer_val_V_2_i_d0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_d0),
    .lineBuffer_val_V_2_i_address1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_address1),
    .lineBuffer_val_V_2_i_ce1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_2_i_ce1),
    .lineBuffer_val_V_2_i_q1(lineBuffer_val_V_2_q1),
    .lineBuffer_val_V_i_address0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_address0),
    .lineBuffer_val_V_i_ce0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_ce0),
    .lineBuffer_val_V_i_we0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_we0),
    .lineBuffer_val_V_i_d0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_d0),
    .lineBuffer_val_V_i_address1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_address1),
    .lineBuffer_val_V_i_ce1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_lineBuffer_val_V_i_ce1),
    .lineBuffer_val_V_i_q1(lineBuffer_val_V_q1),
    .trunc_ln(width),
    .cmp202_i(cmp202_i_reg_498),
    .cmp58_i(cmp58_i_reg_493),
    .p_0_0_01228_224022421_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01228_224022421_i_out),
    .p_0_0_01228_224022421_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01228_224022421_i_out_ap_vld),
    .p_0_0_01229_224002419_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01229_224002419_i_out),
    .p_0_0_01229_224002419_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01229_224002419_i_out_ap_vld),
    .p_0_0_01230_223982417_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01230_223982417_i_out),
    .p_0_0_01230_223982417_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01230_223982417_i_out_ap_vld),
    .right_val_V_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_2_i_out),
    .right_val_V_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_2_i_out_ap_vld),
    .right_val_V_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_1_i_out),
    .right_val_V_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_1_i_out_ap_vld),
    .right_val_V_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_i_out),
    .right_val_V_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_i_out_ap_vld),
    .p_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out),
    .p_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out_ap_vld),
    .p_out1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out1),
    .p_out1_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out1_ap_vld),
    .p_out2(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out2),
    .p_out2_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out2_ap_vld),
    .p_0_2_0_0_01233_12334_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_2_0_0_01233_12334_i_out),
    .p_0_2_0_0_01233_12334_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_2_0_0_01233_12334_i_out_ap_vld),
    .p_0_1_0_0_01232_12331_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_1_0_0_01232_12331_i_out),
    .p_0_1_0_0_01232_12331_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_1_0_0_01232_12331_i_out_ap_vld),
    .p_0_0_0_0_01231_12328_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_0_0_01231_12328_i_out),
    .p_0_0_0_0_01231_12328_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_0_0_01231_12328_i_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln833_fu_223_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_start_reg <= 1'b1;
        end else if ((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_ready == 1'b1)) begin
            grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (bayerPhase_c_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_66 <= 11'd0;
    end else if (((icmp_ln833_fu_223_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        y_fu_66 <= y_6_fu_228_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln833_reg_415 <= add_ln833_fu_205_p2;
        loopHeight_reg_400 <= loopHeight_fu_185_p2;
        trunc_ln825_1_i_reg_410 <= {{bayerPhase_c_dout[15:1]}};
        x_phase_reg_405 <= x_phase_fu_191_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln833_fu_223_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        cmp202_i_reg_498 <= cmp202_i_fu_294_p2;
        cmp58_i_reg_493 <= cmp58_i_fu_289_p2;
        p_0_0_01228_224022422_lcssa2458_i_load_reg_483 <= p_0_0_01228_224022422_lcssa2458_i_fu_114;
        p_0_0_01229_224002420_lcssa2456_i_load_reg_478 <= p_0_0_01229_224002420_lcssa2456_i_fu_110;
        p_0_0_01230_223982418_lcssa2454_i_load_reg_473 <= p_0_0_01230_223982418_lcssa2454_i_fu_106;
        p_0_0_0_0_011942411_lcssa2448_i_load_reg_458 <= p_0_0_0_0_011942411_lcssa2448_i_fu_94;
        p_0_0_0_0_01231_12329_lcssa2371_i_load_reg_428 <= p_0_0_0_0_01231_12329_lcssa2371_i_fu_70;
        p_0_1_0_0_011952413_lcssa2450_i_load_reg_463 <= p_0_1_0_0_011952413_lcssa2450_i_fu_98;
        p_0_1_0_0_01232_12332_lcssa2373_i_load_reg_433 <= p_0_1_0_0_01232_12332_lcssa2373_i_fu_74;
        p_0_2_0_0_011962415_lcssa2452_i_load_reg_468 <= p_0_2_0_0_011962415_lcssa2452_i_fu_102;
        p_0_2_0_0_01233_12335_lcssa2375_i_load_reg_438 <= p_0_2_0_0_01233_12335_lcssa2375_i_fu_78;
        p_lcssa24082442_i_load_reg_443 <= p_lcssa24082442_i_fu_82;
        p_lcssa24092444_i_load_reg_448 <= p_lcssa24092444_i_fu_86;
        p_lcssa24102446_i_load_reg_453 <= p_lcssa24102446_i_fu_90;
        xor_i_reg_488 <= xor_i_fu_284_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        out_y_i_reg_503 <= out_y_i_fu_305_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01228_224022421_i_out_ap_vld == 1'b1))) begin
        p_0_0_01228_224022422_lcssa2458_i_fu_114 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01228_224022421_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01229_224002419_i_out_ap_vld == 1'b1))) begin
        p_0_0_01229_224002420_lcssa2456_i_fu_110 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01229_224002419_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01230_223982417_i_out_ap_vld == 1'b1))) begin
        p_0_0_01230_223982418_lcssa2454_i_fu_106 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_01230_223982417_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_i_out_ap_vld == 1'b1))) begin
        p_0_0_0_0_011942411_lcssa2448_i_fu_94 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_0_0_01231_12328_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_0_0_01231_12329_lcssa2371_i_fu_70 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_0_0_0_01231_12328_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_1_i_out_ap_vld == 1'b1))) begin
        p_0_1_0_0_011952413_lcssa2450_i_fu_98 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_1_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_1_0_0_01232_12331_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_1_0_0_01232_12332_lcssa2373_i_fu_74 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_1_0_0_01232_12331_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_2_i_out_ap_vld == 1'b1))) begin
        p_0_2_0_0_011962415_lcssa2452_i_fu_102 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_right_val_V_2_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_2_0_0_01233_12334_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_2_0_0_01233_12335_lcssa2375_i_fu_78 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_0_2_0_0_01233_12334_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa24082442_i_fu_82 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out1_ap_vld == 1'b1))) begin
        p_lcssa24092444_i_fu_86 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out_ap_vld == 1'b1))) begin
        p_lcssa24102446_i_fu_90 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_p_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        zext_ln833_reg_420[10 : 0] <= zext_ln833_fu_219_p1[10 : 0];
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (bayerPhase_c_empty_n == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln833_fu_223_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln833_fu_223_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c_blk_n = bayerPhase_c_empty_n;
    end else begin
        bayerPhase_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (bayerPhase_c_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c_read = 1'b1;
    end else begin
        bayerPhase_c_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        imgRB_read = grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_imgRB_read;
    end else begin
        imgRB_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        imgRgb_write = grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_imgRgb_write;
    end else begin
        imgRgb_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (bayerPhase_c_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln833_fu_223_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln833_fu_205_p2 = (width + 11'd1);

assign and305_cast_i_fu_280_p1 = out_y_cast_i_fu_274_p2;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (bayerPhase_c_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign cmp202_i_fu_294_p2 = ((y_fu_66 != 11'd0) ? 1'b1 : 1'b0);

assign cmp58_i_fu_289_p2 = ((y_fu_66 < height) ? 1'b1 : 1'b0);

assign empty_130_fu_270_p1 = y_fu_66[0:0];

assign grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_start = grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_ap_start_reg;

assign icmp_ln833_fu_223_p2 = ((y_fu_66 == loopHeight_reg_400) ? 1'b1 : 1'b0);

assign imgRgb_din = grp_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2_fu_144_imgRgb_din;

assign loopHeight_fu_185_p2 = (height + 11'd1);

assign out_y_cast_i_fu_274_p2 = (empty_130_fu_270_p1 ^ 1'd1);

assign out_y_i_fu_305_p2 = ($signed(zext_ln833_reg_420) + $signed(12'd4095));

assign x_phase_fu_191_p1 = bayerPhase_c_dout[0:0];

assign xor_i_fu_284_p2 = (trunc_ln825_1_i_reg_410 ^ and305_cast_i_fu_280_p1);

assign y_6_fu_228_p2 = (y_fu_66 + 11'd1);

assign zext_ln833_fu_219_p1 = y_fu_66;

always @ (posedge ap_clk) begin
    zext_ln833_reg_420[11] <= 1'b0;
end

endmodule //design_1_v_demosaic_0_0_DebayerRandBatG
