// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_1_v_demosaic_0_0_DebayerRatBorBatR (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        imgG_dout,
        imgG_num_data_valid,
        imgG_fifo_cap,
        imgG_empty_n,
        imgG_read,
        imgRB_din,
        imgRB_num_data_valid,
        imgRB_fifo_cap,
        imgRB_full_n,
        imgRB_write,
        height,
        width,
        bayerPhase_c9_dout,
        bayerPhase_c9_num_data_valid,
        bayerPhase_c9_fifo_cap,
        bayerPhase_c9_empty_n,
        bayerPhase_c9_read,
        bayerPhase_c_din,
        bayerPhase_c_num_data_valid,
        bayerPhase_c_fifo_cap,
        bayerPhase_c_full_n,
        bayerPhase_c_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [29:0] imgG_dout;
input  [1:0] imgG_num_data_valid;
input  [1:0] imgG_fifo_cap;
input   imgG_empty_n;
output   imgG_read;
output  [29:0] imgRB_din;
input  [1:0] imgRB_num_data_valid;
input  [1:0] imgRB_fifo_cap;
input   imgRB_full_n;
output   imgRB_write;
input  [10:0] height;
input  [10:0] width;
input  [15:0] bayerPhase_c9_dout;
input  [1:0] bayerPhase_c9_num_data_valid;
input  [1:0] bayerPhase_c9_fifo_cap;
input   bayerPhase_c9_empty_n;
output   bayerPhase_c9_read;
output  [15:0] bayerPhase_c_din;
input  [1:0] bayerPhase_c_num_data_valid;
input  [1:0] bayerPhase_c_fifo_cap;
input   bayerPhase_c_full_n;
output   bayerPhase_c_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg imgG_read;
reg imgRB_write;
reg bayerPhase_c9_read;
reg bayerPhase_c_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    bayerPhase_c9_blk_n;
reg    bayerPhase_c_blk_n;
wire   [10:0] loopHeight_fu_222_p2;
reg   [10:0] loopHeight_reg_488;
wire   [0:0] x_phase_fu_228_p1;
reg   [0:0] x_phase_reg_493;
reg   [14:0] trunc_ln577_1_i_reg_498;
wire   [10:0] add_ln585_fu_242_p2;
reg   [10:0] add_ln585_reg_504;
wire   [11:0] zext_ln585_fu_256_p1;
reg   [11:0] zext_ln585_reg_509;
wire    ap_CS_fsm_state2;
reg   [9:0] p_0_0_0_0_010752214_lcssa2266_i_load_reg_517;
wire   [0:0] icmp_ln585_fu_260_p2;
reg   [9:0] p_0_1_0_0_010762217_lcssa2268_i_load_reg_522;
reg   [9:0] p_0_2_0_0_010772220_lcssa2270_i_load_reg_527;
reg   [9:0] p_0_0_0_0_01075_22244_lcssa2278_i_load_reg_532;
reg   [9:0] p_0_1_0_0_01076_22247_lcssa2280_i_load_reg_537;
reg   [9:0] p_0_2_0_0_01077_22250_lcssa2282_i_load_reg_542;
reg   [9:0] p_0_0_0_0_010382303_lcssa2337_i_load_reg_547;
reg   [9:0] p_0_1_0_0_010392305_lcssa2339_i_load_reg_552;
reg   [9:0] p_0_2_0_0_010402307_lcssa2341_i_load_reg_557;
reg   [9:0] p_lcssa23092343_i_load_reg_562;
reg   [9:0] p_lcssa23102345_i_load_reg_567;
reg   [9:0] p_lcssa23112347_i_load_reg_572;
reg   [9:0] p_0_0_01074_222932312_lcssa2349_i_load_reg_577;
reg   [9:0] p_0_0_01073_222952314_lcssa2351_i_load_reg_582;
reg   [9:0] p_0_0_01072_222972316_lcssa2353_i_load_reg_587;
wire   [0:0] empty_126_fu_316_p1;
reg   [0:0] empty_126_reg_592;
wire   [0:0] cmp58_i_fu_320_p2;
reg   [0:0] cmp58_i_reg_597;
wire   [0:0] cmp202_i_fu_325_p2;
reg   [0:0] cmp202_i_reg_602;
wire   [11:0] out_y_i_fu_336_p2;
reg   [11:0] out_y_i_reg_607;
wire    ap_CS_fsm_state3;
wire   [14:0] xor_i_fu_351_p2;
reg   [14:0] xor_i_reg_612;
wire   [0:0] red_i_fu_357_p2;
reg   [0:0] red_i_reg_617;
wire   [1:0] empty_127_fu_363_p3;
reg   [1:0] empty_127_reg_622;
wire   [1:0] empty_128_fu_372_p3;
reg   [1:0] empty_128_reg_627;
wire   [29:0] lineBuffer_val_V_q1;
wire   [29:0] lineBuffer_val_V_1_q1;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_start;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_done;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_idle;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_ready;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_imgG_read;
wire   [29:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_imgRB_din;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_imgRB_write;
wire   [10:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_address0;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_ce0;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_we0;
wire   [29:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_d0;
wire   [10:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_address1;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_ce1;
wire   [10:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_address0;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_ce0;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_we0;
wire   [29:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_d0;
wire   [10:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_address1;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_ce1;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_red_i;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01072_222972317_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01072_222972317_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01073_222952315_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01073_222952315_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01074_222932313_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01074_222932313_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out1;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out1_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out2;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out2_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010402308_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010402308_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010392306_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010392306_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010382304_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010382304_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_01077_22249_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_01077_22249_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_01076_22246_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_01076_22246_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_01075_22243_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_01075_22243_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010772219_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010772219_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010762216_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010762216_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010752213_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010752213_i_out_ap_vld;
reg    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_start_reg;
wire    ap_CS_fsm_state4;
reg   [9:0] p_0_0_01072_222972316_lcssa2353_i_fu_134;
reg   [9:0] p_0_0_01073_222952314_lcssa2351_i_fu_130;
reg   [9:0] p_0_0_01074_222932312_lcssa2349_i_fu_126;
reg   [9:0] p_lcssa23112347_i_fu_122;
reg   [9:0] p_lcssa23102345_i_fu_118;
reg   [9:0] p_lcssa23092343_i_fu_114;
reg   [9:0] p_0_2_0_0_010402307_lcssa2341_i_fu_110;
reg   [9:0] p_0_1_0_0_010392305_lcssa2339_i_fu_106;
reg   [9:0] p_0_0_0_0_010382303_lcssa2337_i_fu_102;
reg   [9:0] p_0_2_0_0_01077_22250_lcssa2282_i_fu_98;
reg   [9:0] p_0_1_0_0_01076_22247_lcssa2280_i_fu_94;
reg   [9:0] p_0_0_0_0_01075_22244_lcssa2278_i_fu_90;
reg   [9:0] p_0_2_0_0_010772220_lcssa2270_i_fu_86;
reg   [9:0] p_0_1_0_0_010762217_lcssa2268_i_fu_82;
reg   [9:0] p_0_0_0_0_010752214_lcssa2266_i_fu_78;
reg   [10:0] y_fu_74;
wire   [10:0] y_4_fu_265_p2;
reg    ap_block_state1;
wire   [0:0] out_y_cast_i_fu_342_p2;
wire   [14:0] and309_cast_i_fu_347_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_start_reg = 1'b0;
end

design_1_v_demosaic_0_0_DebayerRatBorBatR_lineBuffer_val_V_RAM_AUTO_1R1W #(
    .DataWidth( 30 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
lineBuffer_val_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_address0),
    .ce0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_ce0),
    .we0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_we0),
    .d0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_d0),
    .address1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_address1),
    .ce1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_ce1),
    .q1(lineBuffer_val_V_q1)
);

design_1_v_demosaic_0_0_DebayerRatBorBatR_lineBuffer_val_V_RAM_AUTO_1R1W #(
    .DataWidth( 30 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
lineBuffer_val_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_address0),
    .ce0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_ce0),
    .we0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_we0),
    .d0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_d0),
    .address1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_address1),
    .ce1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_ce1),
    .q1(lineBuffer_val_V_1_q1)
);

design_1_v_demosaic_0_0_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2 grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_start),
    .ap_done(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_done),
    .ap_idle(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_idle),
    .ap_ready(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_ready),
    .imgG_dout(imgG_dout),
    .imgG_num_data_valid(2'd0),
    .imgG_fifo_cap(2'd0),
    .imgG_empty_n(imgG_empty_n),
    .imgG_read(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_imgG_read),
    .imgRB_din(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_imgRB_din),
    .imgRB_num_data_valid(2'd0),
    .imgRB_fifo_cap(2'd0),
    .imgRB_full_n(imgRB_full_n),
    .imgRB_write(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_imgRB_write),
    .p_0_0_01072_222972316_lcssa2353_i(p_0_0_01072_222972316_lcssa2353_i_load_reg_587),
    .p_0_0_01073_222952314_lcssa2351_i(p_0_0_01073_222952314_lcssa2351_i_load_reg_582),
    .p_0_0_01074_222932312_lcssa2349_i(p_0_0_01074_222932312_lcssa2349_i_load_reg_577),
    .p_lcssa23112347_i(p_lcssa23112347_i_load_reg_572),
    .p_lcssa23102345_i(p_lcssa23102345_i_load_reg_567),
    .p_lcssa23092343_i(p_lcssa23092343_i_load_reg_562),
    .p_0_2_0_0_010402307_lcssa2341_i(p_0_2_0_0_010402307_lcssa2341_i_load_reg_557),
    .p_0_1_0_0_010392305_lcssa2339_i(p_0_1_0_0_010392305_lcssa2339_i_load_reg_552),
    .p_0_0_0_0_010382303_lcssa2337_i(p_0_0_0_0_010382303_lcssa2337_i_load_reg_547),
    .p_0_2_0_0_01077_22250_lcssa2282_i(p_0_2_0_0_01077_22250_lcssa2282_i_load_reg_542),
    .p_0_1_0_0_01076_22247_lcssa2280_i(p_0_1_0_0_01076_22247_lcssa2280_i_load_reg_537),
    .p_0_0_0_0_01075_22244_lcssa2278_i(p_0_0_0_0_01075_22244_lcssa2278_i_load_reg_532),
    .p_0_2_0_0_010772220_lcssa2270_i(p_0_2_0_0_010772220_lcssa2270_i_load_reg_527),
    .p_0_1_0_0_010762217_lcssa2268_i(p_0_1_0_0_010762217_lcssa2268_i_load_reg_522),
    .p_0_0_0_0_010752214_lcssa2266_i(p_0_0_0_0_010752214_lcssa2266_i_load_reg_517),
    .add_ln585_i(add_ln585_reg_504),
    .out_y_i(out_y_i_reg_607),
    .x_phase_i(x_phase_reg_493),
    .xor_i(xor_i_reg_612),
    .lineBuffer_val_V_1_i_address0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_address0),
    .lineBuffer_val_V_1_i_ce0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_ce0),
    .lineBuffer_val_V_1_i_we0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_we0),
    .lineBuffer_val_V_1_i_d0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_d0),
    .lineBuffer_val_V_1_i_address1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_address1),
    .lineBuffer_val_V_1_i_ce1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_1_i_ce1),
    .lineBuffer_val_V_1_i_q1(lineBuffer_val_V_1_q1),
    .lineBuffer_val_V_i_address0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_address0),
    .lineBuffer_val_V_i_ce0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_ce0),
    .lineBuffer_val_V_i_we0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_we0),
    .lineBuffer_val_V_i_d0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_d0),
    .lineBuffer_val_V_i_address1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_address1),
    .lineBuffer_val_V_i_ce1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_lineBuffer_val_V_i_ce1),
    .lineBuffer_val_V_i_q1(lineBuffer_val_V_q1),
    .trunc_ln(width),
    .cmp202_i(cmp202_i_reg_602),
    .cmp58_i(cmp58_i_reg_597),
    .empty_49(empty_128_reg_627),
    .red_i(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_red_i),
    .empty(empty_127_reg_622),
    .p_0_0_01072_222972317_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01072_222972317_i_out),
    .p_0_0_01072_222972317_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01072_222972317_i_out_ap_vld),
    .p_0_0_01073_222952315_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01073_222952315_i_out),
    .p_0_0_01073_222952315_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01073_222952315_i_out_ap_vld),
    .p_0_0_01074_222932313_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01074_222932313_i_out),
    .p_0_0_01074_222932313_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01074_222932313_i_out_ap_vld),
    .p_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out),
    .p_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out_ap_vld),
    .p_out1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out1),
    .p_out1_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out1_ap_vld),
    .p_out2(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out2),
    .p_out2_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out2_ap_vld),
    .p_0_2_0_0_010402308_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010402308_i_out),
    .p_0_2_0_0_010402308_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010402308_i_out_ap_vld),
    .p_0_1_0_0_010392306_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010392306_i_out),
    .p_0_1_0_0_010392306_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010392306_i_out_ap_vld),
    .p_0_0_0_0_010382304_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010382304_i_out),
    .p_0_0_0_0_010382304_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010382304_i_out_ap_vld),
    .p_0_2_0_0_01077_22249_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_01077_22249_i_out),
    .p_0_2_0_0_01077_22249_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_01077_22249_i_out_ap_vld),
    .p_0_1_0_0_01076_22246_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_01076_22246_i_out),
    .p_0_1_0_0_01076_22246_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_01076_22246_i_out_ap_vld),
    .p_0_0_0_0_01075_22243_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_01075_22243_i_out),
    .p_0_0_0_0_01075_22243_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_01075_22243_i_out_ap_vld),
    .p_0_2_0_0_010772219_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010772219_i_out),
    .p_0_2_0_0_010772219_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010772219_i_out_ap_vld),
    .p_0_1_0_0_010762216_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010762216_i_out),
    .p_0_1_0_0_010762216_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010762216_i_out_ap_vld),
    .p_0_0_0_0_010752213_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010752213_i_out),
    .p_0_0_0_0_010752213_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010752213_i_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln585_fu_260_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_start_reg <= 1'b1;
        end else if ((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_ready == 1'b1)) begin
            grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((bayerPhase_c_full_n == 1'b0) | (bayerPhase_c9_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_74 <= 11'd0;
    end else if (((icmp_ln585_fu_260_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        y_fu_74 <= y_4_fu_265_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln585_reg_504 <= add_ln585_fu_242_p2;
        loopHeight_reg_488 <= loopHeight_fu_222_p2;
        trunc_ln577_1_i_reg_498 <= {{bayerPhase_c9_dout[15:1]}};
        x_phase_reg_493 <= x_phase_fu_228_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln585_fu_260_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        cmp202_i_reg_602 <= cmp202_i_fu_325_p2;
        cmp58_i_reg_597 <= cmp58_i_fu_320_p2;
        empty_126_reg_592 <= empty_126_fu_316_p1;
        p_0_0_01072_222972316_lcssa2353_i_load_reg_587 <= p_0_0_01072_222972316_lcssa2353_i_fu_134;
        p_0_0_01073_222952314_lcssa2351_i_load_reg_582 <= p_0_0_01073_222952314_lcssa2351_i_fu_130;
        p_0_0_01074_222932312_lcssa2349_i_load_reg_577 <= p_0_0_01074_222932312_lcssa2349_i_fu_126;
        p_0_0_0_0_010382303_lcssa2337_i_load_reg_547 <= p_0_0_0_0_010382303_lcssa2337_i_fu_102;
        p_0_0_0_0_010752214_lcssa2266_i_load_reg_517 <= p_0_0_0_0_010752214_lcssa2266_i_fu_78;
        p_0_0_0_0_01075_22244_lcssa2278_i_load_reg_532 <= p_0_0_0_0_01075_22244_lcssa2278_i_fu_90;
        p_0_1_0_0_010392305_lcssa2339_i_load_reg_552 <= p_0_1_0_0_010392305_lcssa2339_i_fu_106;
        p_0_1_0_0_010762217_lcssa2268_i_load_reg_522 <= p_0_1_0_0_010762217_lcssa2268_i_fu_82;
        p_0_1_0_0_01076_22247_lcssa2280_i_load_reg_537 <= p_0_1_0_0_01076_22247_lcssa2280_i_fu_94;
        p_0_2_0_0_010402307_lcssa2341_i_load_reg_557 <= p_0_2_0_0_010402307_lcssa2341_i_fu_110;
        p_0_2_0_0_010772220_lcssa2270_i_load_reg_527 <= p_0_2_0_0_010772220_lcssa2270_i_fu_86;
        p_0_2_0_0_01077_22250_lcssa2282_i_load_reg_542 <= p_0_2_0_0_01077_22250_lcssa2282_i_fu_98;
        p_lcssa23092343_i_load_reg_562 <= p_lcssa23092343_i_fu_114;
        p_lcssa23102345_i_load_reg_567 <= p_lcssa23102345_i_fu_118;
        p_lcssa23112347_i_load_reg_572 <= p_lcssa23112347_i_fu_122;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        empty_127_reg_622[1] <= empty_127_fu_363_p3[1];
        empty_128_reg_627[1] <= empty_128_fu_372_p3[1];
        out_y_i_reg_607 <= out_y_i_fu_336_p2;
        red_i_reg_617 <= red_i_fu_357_p2;
        xor_i_reg_612 <= xor_i_fu_351_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01072_222972317_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_01072_222972316_lcssa2353_i_fu_134 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01072_222972317_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01073_222952315_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_01073_222952314_lcssa2351_i_fu_130 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01073_222952315_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01074_222932313_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_01074_222932312_lcssa2349_i_fu_126 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_01074_222932313_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010382304_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_0_0_010382303_lcssa2337_i_fu_102 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010382304_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010752213_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_0_0_010752214_lcssa2266_i_fu_78 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_010752213_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_01075_22243_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_0_0_01075_22244_lcssa2278_i_fu_90 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_0_0_0_01075_22243_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010392306_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_1_0_0_010392305_lcssa2339_i_fu_106 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010392306_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010762216_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_1_0_0_010762217_lcssa2268_i_fu_82 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_010762216_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_01076_22246_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_1_0_0_01076_22247_lcssa2280_i_fu_94 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_1_0_0_01076_22246_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010402308_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_2_0_0_010402307_lcssa2341_i_fu_110 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010402308_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010772219_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_2_0_0_010772220_lcssa2270_i_fu_86 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_010772219_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_01077_22249_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_2_0_0_01077_22250_lcssa2282_i_fu_98 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_0_2_0_0_01077_22249_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa23092343_i_fu_114 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa23102345_i_fu_118 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa23112347_i_fu_122 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_p_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        zext_ln585_reg_509[10 : 0] <= zext_ln585_fu_256_p1[10 : 0];
    end
end

always @ (*) begin
    if (((bayerPhase_c_full_n == 1'b0) | (bayerPhase_c9_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln585_fu_260_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c9_blk_n = bayerPhase_c9_empty_n;
    end else begin
        bayerPhase_c9_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((bayerPhase_c_full_n == 1'b0) | (bayerPhase_c9_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c9_read = 1'b1;
    end else begin
        bayerPhase_c9_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c_blk_n = bayerPhase_c_full_n;
    end else begin
        bayerPhase_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((bayerPhase_c_full_n == 1'b0) | (bayerPhase_c9_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c_write = 1'b1;
    end else begin
        bayerPhase_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        imgG_read = grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_imgG_read;
    end else begin
        imgG_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        imgRB_write = grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_imgRB_write;
    end else begin
        imgRB_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln585_fu_260_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((bayerPhase_c_full_n == 1'b0) | (bayerPhase_c9_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln585_fu_260_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln585_fu_242_p2 = (width + 11'd1);

assign and309_cast_i_fu_347_p1 = out_y_cast_i_fu_342_p2;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((bayerPhase_c_full_n == 1'b0) | (bayerPhase_c9_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign bayerPhase_c_din = bayerPhase_c9_dout;

assign cmp202_i_fu_325_p2 = ((y_fu_74 != 11'd0) ? 1'b1 : 1'b0);

assign cmp58_i_fu_320_p2 = ((y_fu_74 < height) ? 1'b1 : 1'b0);

assign empty_126_fu_316_p1 = y_fu_74[0:0];

assign empty_127_fu_363_p3 = ((red_i_fu_357_p2[0:0] == 1'b1) ? 2'd0 : 2'd2);

assign empty_128_fu_372_p3 = ((red_i_fu_357_p2[0:0] == 1'b1) ? 2'd2 : 2'd0);

assign grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_start = grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_ap_start_reg;

assign grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_red_i = red_i_reg_617;

assign icmp_ln585_fu_260_p2 = ((y_fu_74 == loopHeight_reg_488) ? 1'b1 : 1'b0);

assign imgRB_din = grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_588_2_fu_172_imgRB_din;

assign loopHeight_fu_222_p2 = (height + 11'd1);

assign out_y_cast_i_fu_342_p2 = (empty_126_reg_592 ^ 1'd1);

assign out_y_i_fu_336_p2 = ($signed(zext_ln585_reg_509) + $signed(12'd4095));

assign red_i_fu_357_p2 = ((and309_cast_i_fu_347_p1 == trunc_ln577_1_i_reg_498) ? 1'b1 : 1'b0);

assign start_out = real_start;

assign x_phase_fu_228_p1 = bayerPhase_c9_dout[0:0];

assign xor_i_fu_351_p2 = (trunc_ln577_1_i_reg_498 ^ and309_cast_i_fu_347_p1);

assign y_4_fu_265_p2 = (y_fu_74 + 11'd1);

assign zext_ln585_fu_256_p1 = y_fu_74;

always @ (posedge ap_clk) begin
    zext_ln585_reg_509[11] <= 1'b0;
    empty_127_reg_622[0] <= 1'b0;
    empty_128_reg_627[0] <= 1'b0;
end

endmodule //design_1_v_demosaic_0_0_DebayerRatBorBatR
